### ISSUE TITLE
Problem with SERVER_MODE=true

### ISSUE THREAD

**Issue by jonatasoli** [foxylion/docker-pgadmin4#4]
Hello,

I try use this is image with server_mode but when i input SERVER_MODE=true the container not work. I need add other parameter?

Thanks

**Comment by foxylion** [comment]
Hi jonatasoli,
i would recommend you to use `dpage/pgadmin4:2.0` this is now the public available docker image for pgAdmin 4.

If you would like to get this bug resolved I can dig into it. But maybe the official image does solve your problem.

**Comment by jonatasoli** [comment]
Thank you :+1:
